// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCS-Dh7e1Y8tO94bSMLEUYnul0BSIU1sE',
    appId: '1:396925257081:web:fcd508cfcde428cd581ba8',
    messagingSenderId: '396925257081',
    projectId: 'test-firebase-dcc7d',
    authDomain: 'test-firebase-dcc7d.firebaseapp.com',
    storageBucket: 'test-firebase-dcc7d.firebasestorage.app',
    measurementId: 'G-D0DVRYY6CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi-9c2gIR0POK178fYS0zhX19a3bBUZ3U',
    appId: '1:396925257081:android:4d5bd6470fa5eefc581ba8',
    messagingSenderId: '396925257081',
    projectId: 'test-firebase-dcc7d',
    storageBucket: 'test-firebase-dcc7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEDpZm9_Fq_VUNzrn7qKGb4xXUyXcMnEA',
    appId: '1:396925257081:ios:8911181db08c243d581ba8',
    messagingSenderId: '396925257081',
    projectId: 'test-firebase-dcc7d',
    storageBucket: 'test-firebase-dcc7d.firebasestorage.app',
    iosBundleId: 'com.example.testFirewall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEDpZm9_Fq_VUNzrn7qKGb4xXUyXcMnEA',
    appId: '1:396925257081:ios:8911181db08c243d581ba8',
    messagingSenderId: '396925257081',
    projectId: 'test-firebase-dcc7d',
    storageBucket: 'test-firebase-dcc7d.firebasestorage.app',
    iosBundleId: 'com.example.testFirewall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCS-Dh7e1Y8tO94bSMLEUYnul0BSIU1sE',
    appId: '1:396925257081:web:5758953c880d7460581ba8',
    messagingSenderId: '396925257081',
    projectId: 'test-firebase-dcc7d',
    authDomain: 'test-firebase-dcc7d.firebaseapp.com',
    storageBucket: 'test-firebase-dcc7d.firebasestorage.app',
    measurementId: 'G-YFQDLZ7K7Z',
  );
}
